name: 2.01 - Manual Trigger Workflow (Day 2 Ex 1)

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Where do you live'
        required: true
        default: 'Berlin'
        type: string

jobs:
  greet:
    runs-on: ubuntu-latest
    steps:
      - name: Greet User
        run: echo "Hello, you live in ${{ github.event.inputs.name }}!"